class ObservationLimits:
    POSITION_X_MIN = -14.385
    POSITION_X_MAX = 16.385
    POSITION_Y_MIN = -8.585
    POSITION_Y_MAX = 8.585
    MAX_DISTANCE = 32.0
    SKELETON_HEALTH_MIN = 0.0
    SKELETON_HEALTH_MAX = 20.0
    BOMBKID_HEALTH_MIN = 0.0
    BOMBKID_HEALTH_MAX = 1.0
    TURRET_HEALTH_MIN = 0.0
    TURRET_HEALTH_MAX = 100.0


__all__ = ["ObservationLimits"]
